steps:

# TRAIN IMAGE
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build training image'
  args:
    - build
    - -f
    - dockerfiles/train.dockerfile
    - -t
    - europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-project-group65-docker/train:latest
    - .

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push training image'
  args:
    - push
    - europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-project-group65-docker/train:latest

# API IMAGE
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build api image'
  args:
    - build
    - -f
    - dockerfiles/api.dockerfile
    - -t
    - europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-project-group65-docker/api:latest
    - .

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push api image'
  args:
    - push
    - europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-project-group65-docker/api:latest

# Deploy cloud run service
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy API to Cloud Run'
  args:
    - run
    - deploy
    - mlops-api
    - --image
    - europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-project-group65-docker/api:latest
    - --region
    - europe-west1
    - --platform
    - managed
    - --allow-unauthenticated
    - --port
    - "8080"
    - --memory
    - "4Gi"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _REPO: mlops-project-group65-docker
  _SERVICE: mlops-api